workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'

stages:
  - test
  - stress-test
  - publish

default:
  cache:
    key: pip-cache
    paths:
      - .cache/pip

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

unit-tests:
  stage: test
  tags: [self-hosted]
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
  script:
    - python3 -m pip install --upgrade pip
    - pip install -e .
    - pip install pytest pytest-asyncio pytest-cov beautifulsoup4 httpx
    - export PATH="$HOME/.local/bin:$PATH"
    - cd tests
    - pytest unit -v --tb=short --cov=fpx --cov-report=xml --cov-report=term
  artifacts:
    when: always
    paths:
      - tests/coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml

stress-tests:
  stage: stress-test
  tags: [self-hosted]
  needs: ["unit-tests"]
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
  script:
    - python3 -m pip install --upgrade pip
    - pip install -e .
    - pip install pytest pytest-asyncio beautifulsoup4 httpx
    - export PATH="$HOME/.local/bin:$PATH"
    - cd tests
    - pytest stress -v --tb=short -m stress

publish:
  stage: publish
  tags: [self-hosted]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  id_tokens:
    PYPI_ID_TOKEN:
      aud: pypi
  script:
    - python3 -m pip install --upgrade pip
    - pip install build twine
    - python3 -m build
    - twine upload dist/*
