site_name: fpx-engine
site_description: Асинхронный фреймворк для автоматизации FunPay на Python.
site_author: bymyforge

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - code.copy
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Включить тёмную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Включить светлую тему

nav:
  - Главная: index.md
  - Быстрый старт: quickstart.md
  - Роутер и хендлеры: router.md
  - Модели: models.md
  - Функционал:
    - Чаты и сообщения: chat.md
    - Заказы: orders.md
    - Покупки: purchases.md
    - Отзывы: review.md
    - Профиль и баланс: profile.md
    - Лоты и поднятие: lots.md
    - Редактор лотов: editor.md
    - Мониторинг категорий: category.md
    - Логи: logging.md
    - Создание лотов: lot_creator.md
  - Машина состояний: fsm.md
  - Ошибки: errors.md
  - API: api.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search